# Generated by Django 3.2.13 on 2026-01-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ci_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='maternal_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='paternal_surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
