# Generated by Django 3.2.13 on 2026-01-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_auto_20260107_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
