# Generated by Django 3.2.13 on 2026-01-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
