# Generated by Django 3.2.13 on 2026-02-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_specialcriterionscore'),
        ('api_user', '0008_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='school.course'),
        ),
    ]
