# Generated by Django 3.2.13 on 2026-02-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('stock', models.IntegerField(default=0, verbose_name='Existencias')),
                ('pages', models.IntegerField(verbose_name='Páginas')),
                ('dl', models.CharField(blank=True, max_length=100, null=True, verbose_name='Depósito Legal')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
