# Generated by Django 3.2.13 on 2026-02-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_image', models.ImageField(blank=True, null=True, upload_to='landing-page/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configuration',
            },
        ),
    ]
