# Generated by Django 3.2.13 on 2026-01-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_evaluationcriterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='evaluationcriterion',
            name='subject',
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='evaluation_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='school.evaluationtemplate'),
        ),
        migrations.AddField(
            model_name='subject',
            name='evaluation_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.evaluationtemplate'),
        ),
    ]
