# Generated by Django 3.2.13 on 2026-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20260107_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcriterion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
