# Generated by Django 3.2.13 on 2026-01-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20260107_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subcriteria_locked',
            field=models.BooleanField(default=False),
        ),
    ]
