# Generated by Django 3.2.13 on 2026-01-07 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0006_subject_subcriteria_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='group_name',
            new_name='parallel',
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
