# Generated by Django 3.2.13 on 2026-01-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20260107_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSubCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria', to='school.course')),
                ('parent_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_sub_criteria', to='school.evaluationcriterion')),
            ],
        ),
    ]
