# Generated by Django 3.2.13 on 2026-01-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_coursesubcriterion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subcriteria_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CourseSpecialCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_criteria', to='school.course')),
            ],
        ),
    ]
