# Generated by Django 3.2.13 on 2026-01-13 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20260112_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespecialcriterion',
            name='parent_criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_special_criteria', to='school.evaluationcriterion'),
        ),
    ]
