# Generated by Django 3.2.13 on 2026-01-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_coursespecialcriterion_parent_criterion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_scores', to='school.enrollment')),
                ('sub_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.coursesubcriterion')),
            ],
            options={
                'unique_together': {('enrollment', 'sub_criterion')},
            },
        ),
    ]
