# Generated by Django 3.2.13 on 2026-01-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_criterionscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcriterion',
            name='editable_on_gradesheet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursesubcriterion',
            name='visible_on_gradesheet',
            field=models.BooleanField(default=True),
        ),
    ]
