# Generated by Django 3.2.13 on 2026-01-26 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20260114_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=1, help_text='Weight of the task (e.g., 2 means it counts as 2 tasks)')),
                ('sub_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.coursesubcriterion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_scores', to='school.enrollment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.coursetask')),
            ],
            options={
                'unique_together': {('enrollment', 'task')},
            },
        ),
    ]
