# Generated by Django 3.2.13 on 2026-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_coursetask_taskscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coursetask',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
