# Generated by Django 3.2.13 on 2026-01-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20260127_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='school.course')),
                ('members', models.ManyToManyField(related_name='projects', to='school.Enrollment')),
                ('student_in_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='school.enrollment')),
                ('sub_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='school.coursesubcriterion')),
            ],
        ),
    ]
