# Generated by Django 3.2.13 on 2026-01-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcriterion',
            name='is_project',
            field=models.BooleanField(default=False, help_text='If true, this criterion requires group projects instead of individual tasks'),
        ),
    ]
