# Generated by Django 3.2.13 on 2026-01-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_coursesubcriterion_is_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcriterion',
            name='max_members',
            field=models.IntegerField(blank=True, help_text='Maximum number of members per project group', null=True),
        ),
    ]
