# Generated by Django 3.2.13 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_coursesubcriterion_max_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcriterion',
            name='is_project_registration_open',
            field=models.BooleanField(default=False),
        ),
    ]
