# Generated by Django 3.2.13 on 2026-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_coursesubcriterion_is_project_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubcriterion',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursesubcriterion',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
