# Generated by Django 3.2.13 on 2026-02-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20260203_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_registration_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('paternal_surname', models.CharField(max_length=100)),
                ('maternal_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('cellphone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='school.course')),
            ],
            options={
                'unique_together': {('course', 'ci')},
            },
        ),
    ]
