# Generated by Django 3.2.13 on 2026-02-08 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetask',
            name='special_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.coursespecialcriterion'),
        ),
        migrations.AlterField(
            model_name='coursetask',
            name='sub_criterion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.coursesubcriterion'),
        ),
    ]
