# Generated by Django 3.2.13 on 2026-02-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20260207_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespecialcriterion',
            name='editable_on_gradesheet',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='coursespecialcriterion',
            name='visible_on_gradesheet',
            field=models.BooleanField(default=True),
        ),
    ]
