# Generated by Django 3.2.13 on 2026-02-09 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20260208_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcriterion',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='evaluationcriterion',
            name='start_date',
        ),
    ]
