# Generated by Django 3.2.13 on 2026-02-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20260208_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
