# Generated by Django 3.2.13 on 2026-02-09 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_alter_course_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialCriterionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_criterion_scores', to='school.enrollment')),
                ('special_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='school.coursespecialcriterion')),
            ],
            options={
                'unique_together': {('enrollment', 'special_criterion')},
            },
        ),
    ]
