# Generated by Django 3.2.13 on 2026-02-19 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0026_specialcriterionscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_tab', models.CharField(blank=True, help_text="ID or 'special-ID'", max_length=50, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='school.course')),
                ('last_sub_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.coursesubcriterion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
