# Generated by Django 3.2.13 on 2026-03-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_coursepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_identifier',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='platform_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
